-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.assessment_sessions
(
    id serial NOT NULL,
    assessment_id integer NOT NULL,
    user_id integer,
    guest_session_id integer,
    current_stage_id integer NOT NULL,
    completed boolean DEFAULT false,
    started_at timestamp without time zone DEFAULT now(),
    completed_at timestamp without time zone,
    CONSTRAINT assessment_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT one_attempt_per_user UNIQUE (assessment_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.assessment_stages
(
    id serial NOT NULL,
    assessment_id integer NOT NULL,
    stage_order integer NOT NULL,
    energy_center_id integer,
    requires_auth boolean DEFAULT false,
    description text COLLATE pg_catalog."default",
    CONSTRAINT assessment_stages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.assessments
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT assessments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.energy_centers
(
    id integer NOT NULL,
    code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT energy_centers_pkey PRIMARY KEY (id),
    CONSTRAINT energy_centers_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.energy_group_responses
(
    id integer NOT NULL DEFAULT nextval('group_responses_id_seq'::regclass),
    session_id uuid,
    energy_statement_group_id integer,
    submitted_at timestamp without time zone DEFAULT now(),
    CONSTRAINT group_responses_pkey PRIMARY KEY (id),
    CONSTRAINT group_responses_session_id_group_id_key UNIQUE (session_id, energy_statement_group_id)
);

CREATE TABLE IF NOT EXISTS public.energy_result_eligible_centers
(
    id serial NOT NULL,
    session_id uuid NOT NULL,
    energy_center character varying(10) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT energy_result_eligible_centers_pkey PRIMARY KEY (id),
    CONSTRAINT uq_energy_result_eligible UNIQUE (session_id, energy_center)
);

CREATE TABLE IF NOT EXISTS public.energy_results
(
    session_id uuid NOT NULL,
    dominant_center character varying(10) COLLATE pg_catalog."default",
    gut_score integer NOT NULL,
    heart_score integer NOT NULL,
    head_score integer NOT NULL,
    calculated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT test_results_pkey PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS public.energy_statement_groups
(
    id integer NOT NULL DEFAULT nextval('question_groups_id_seq'::regclass),
    stage_id integer,
    group_no integer NOT NULL,
    CONSTRAINT question_groups_pkey PRIMARY KEY (id),
    CONSTRAINT question_groups_stage_id_group_no_key UNIQUE (stage_id, group_no)
);

CREATE TABLE IF NOT EXISTS public.energy_statement_rankings
(
    group_response_id integer NOT NULL,
    statement_id integer NOT NULL,
    rank_id smallint,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT statement_rankings_pkey PRIMARY KEY (group_response_id, statement_id),
    CONSTRAINT statement_rankings_group_response_id_rank_id_key UNIQUE (group_response_id, rank_id)
);

CREATE TABLE IF NOT EXISTS public.energy_statements
(
    id integer NOT NULL DEFAULT nextval('statements_id_seq'::regclass),
    group_id integer,
    personality_type character varying(10) COLLATE pg_catalog."default",
    text text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT statements_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.guest_sessions
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT guest_sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.personality_answer_options
(
    id integer NOT NULL DEFAULT nextval('answer_options_id_seq'::regclass),
    question_id integer NOT NULL,
    text text COLLATE pg_catalog."default" NOT NULL,
    personality_type_id integer NOT NULL,
    score integer NOT NULL,
    CONSTRAINT answer_options_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.personality_interpretations
(
    id serial NOT NULL,
    session_id uuid NOT NULL,
    stage_id integer NOT NULL,
    primary_personality_type_id integer NOT NULL,
    secondary_personality_type_id integer,
    interpretation_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    notes text COLLATE pg_catalog."default",
    interpreted_at timestamp without time zone DEFAULT now(),
    CONSTRAINT personality_interpretations_pkey PRIMARY KEY (id),
    CONSTRAINT uq_personality_interpretation UNIQUE (session_id, stage_id)
);

CREATE TABLE IF NOT EXISTS public.personality_questions
(
    id integer NOT NULL DEFAULT nextval('questions_id_seq'::regclass),
    stage_id integer NOT NULL,
    text text COLLATE pg_catalog."default" NOT NULL,
    question_order integer NOT NULL,
    CONSTRAINT questions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.personality_responses
(
    id integer NOT NULL DEFAULT nextval('responses_id_seq'::regclass),
    personality_session_id integer NOT NULL,
    question_id integer NOT NULL,
    answer_option_id integer NOT NULL,
    answered_at timestamp without time zone DEFAULT now(),
    CONSTRAINT responses_pkey PRIMARY KEY (id),
    CONSTRAINT one_answer_per_question UNIQUE (personality_session_id, question_id)
);

CREATE TABLE IF NOT EXISTS public.personality_result_breakdown
(
    id serial NOT NULL,
    personality_session_id integer NOT NULL,
    personality_type_id integer NOT NULL,
    score integer NOT NULL,
    calculated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT personality_result_breakdown_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.personality_result_types
(
    id serial NOT NULL,
    personality_result_id integer NOT NULL,
    personality_type_id integer NOT NULL,
    score integer NOT NULL,
    rank integer NOT NULL,
    CONSTRAINT personality_result_types_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.personality_results
(
    id integer NOT NULL DEFAULT nextval('assessment_results_id_seq'::regclass),
    personality_session_id integer NOT NULL,
    gut_score integer NOT NULL,
    heart_score integer NOT NULL,
    head_score integer NOT NULL,
    dominant_personality_type_id integer NOT NULL,
    calculated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT assessment_results_pkey PRIMARY KEY (id),
    CONSTRAINT assessment_results_session_id_key UNIQUE (personality_session_id)
);

CREATE TABLE IF NOT EXISTS public.personality_sessions
(
    id serial NOT NULL,
    test_session_id uuid NOT NULL,
    energy_center character varying(10) COLLATE pg_catalog."default" NOT NULL,
    started_at timestamp without time zone DEFAULT now(),
    completed_at timestamp without time zone,
    CONSTRAINT personality_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_personality_session UNIQUE (test_session_id, energy_center)
);

CREATE TABLE IF NOT EXISTS public.personality_types
(
    id serial NOT NULL,
    code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT personality_types_pkey PRIMARY KEY (id),
    CONSTRAINT personality_types_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.rank_choices
(
    id smallint NOT NULL,
    label character varying(20) COLLATE pg_catalog."default" NOT NULL,
    weight integer NOT NULL,
    CONSTRAINT rank_choices_pkey PRIMARY KEY (id),
    CONSTRAINT rank_choices_label_key UNIQUE (label)
);

CREATE TABLE IF NOT EXISTS public.stages
(
    id serial NOT NULL,
    code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT stages_pkey PRIMARY KEY (id),
    CONSTRAINT stages_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.test_sessions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id integer,
    guest_email text COLLATE pg_catalog."default",
    started_at timestamp without time zone DEFAULT now(),
    completed_at timestamp without time zone,
    stage2_unlocked_at timestamp without time zone,
    stage1_completed_at timestamp without time zone,
    CONSTRAINT test_sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    role character varying(10) COLLATE pg_catalog."default" DEFAULT 'USER'::character varying,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.assessment_sessions
    ADD CONSTRAINT assessment_sessions_assessment_id_fkey FOREIGN KEY (assessment_id)
    REFERENCES public.assessments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.assessment_sessions
    ADD CONSTRAINT assessment_sessions_current_stage_id_fkey FOREIGN KEY (current_stage_id)
    REFERENCES public.assessment_stages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.assessment_sessions
    ADD CONSTRAINT assessment_sessions_guest_session_id_fkey FOREIGN KEY (guest_session_id)
    REFERENCES public.guest_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.assessment_sessions
    ADD CONSTRAINT assessment_sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.assessment_stages
    ADD CONSTRAINT assessment_stages_assessment_id_fkey FOREIGN KEY (assessment_id)
    REFERENCES public.assessments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.assessment_stages
    ADD CONSTRAINT assessment_stages_energy_center_fk FOREIGN KEY (energy_center_id)
    REFERENCES public.energy_centers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.assessment_stages
    ADD CONSTRAINT assessment_stages_personality_type_id_fkey FOREIGN KEY (energy_center_id)
    REFERENCES public.personality_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.energy_group_responses
    ADD CONSTRAINT energy_group_responses_energy_statement_group_id_fkey FOREIGN KEY (energy_statement_group_id)
    REFERENCES public.energy_statement_groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.energy_group_responses
    ADD CONSTRAINT group_responses_group_id_fkey FOREIGN KEY (energy_statement_group_id)
    REFERENCES public.energy_statement_groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.energy_group_responses
    ADD CONSTRAINT group_responses_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES public.test_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.energy_result_eligible_centers
    ADD CONSTRAINT fk_energy_result_eligible_session FOREIGN KEY (session_id)
    REFERENCES public.test_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.energy_results
    ADD CONSTRAINT test_results_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES public.test_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS test_results_pkey
    ON public.energy_results(session_id);


ALTER TABLE IF EXISTS public.energy_statement_groups
    ADD CONSTRAINT question_groups_stage_id_fkey FOREIGN KEY (stage_id)
    REFERENCES public.stages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.energy_statement_rankings
    ADD CONSTRAINT statement_rankings_group_response_id_fkey FOREIGN KEY (group_response_id)
    REFERENCES public.energy_group_responses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.energy_statement_rankings
    ADD CONSTRAINT statement_rankings_rank_id_fkey FOREIGN KEY (rank_id)
    REFERENCES public.rank_choices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.energy_statement_rankings
    ADD CONSTRAINT statement_rankings_statement_id_fkey FOREIGN KEY (statement_id)
    REFERENCES public.energy_statements (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.energy_statements
    ADD CONSTRAINT statements_group_id_fkey FOREIGN KEY (group_id)
    REFERENCES public.energy_statement_groups (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.personality_answer_options
    ADD CONSTRAINT answer_options_personality_type_id_fkey FOREIGN KEY (personality_type_id)
    REFERENCES public.personality_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personality_answer_options
    ADD CONSTRAINT answer_options_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.personality_questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personality_interpretations
    ADD CONSTRAINT fk_pi_primary FOREIGN KEY (primary_personality_type_id)
    REFERENCES public.personality_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personality_interpretations
    ADD CONSTRAINT fk_pi_secondary FOREIGN KEY (secondary_personality_type_id)
    REFERENCES public.personality_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personality_interpretations
    ADD CONSTRAINT fk_pi_session FOREIGN KEY (session_id)
    REFERENCES public.test_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.personality_interpretations
    ADD CONSTRAINT fk_pi_stage FOREIGN KEY (stage_id)
    REFERENCES public.assessment_stages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personality_questions
    ADD CONSTRAINT questions_stage_id_fkey FOREIGN KEY (stage_id)
    REFERENCES public.assessment_stages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personality_responses
    ADD CONSTRAINT responses_answer_option_id_fkey FOREIGN KEY (answer_option_id)
    REFERENCES public.personality_answer_options (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personality_responses
    ADD CONSTRAINT responses_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.personality_questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personality_responses
    ADD CONSTRAINT responses_session_id_fkey FOREIGN KEY (personality_session_id)
    REFERENCES public.assessment_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personality_result_breakdown
    ADD CONSTRAINT fk_prb_personality_session FOREIGN KEY (personality_session_id)
    REFERENCES public.personality_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.personality_result_breakdown
    ADD CONSTRAINT fk_prb_personality_type FOREIGN KEY (personality_type_id)
    REFERENCES public.personality_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personality_results
    ADD CONSTRAINT assessment_results_dominant_personality_type_id_fkey FOREIGN KEY (dominant_personality_type_id)
    REFERENCES public.personality_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.personality_results
    ADD CONSTRAINT assessment_results_session_id_fkey FOREIGN KEY (personality_session_id)
    REFERENCES public.assessment_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS assessment_results_session_id_key
    ON public.personality_results(personality_session_id);


ALTER TABLE IF EXISTS public.personality_sessions
    ADD CONSTRAINT fk_personality_session_test FOREIGN KEY (test_session_id)
    REFERENCES public.test_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.test_sessions
    ADD CONSTRAINT test_sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS one_test_per_user
    ON public.test_sessions(user_id);

END;