### List all sessions
GET http://localhost:3000/


### 1 - Create a new session
POST http://localhost:3000/sessions/start
Content-Type: application/json

{
  "email": "test@test.com"
}


### 2a - Get session details
GET http://localhost:3000/energy/next/11e653aa-4c30-4eac-9f5b-e1b5274f01da



### 2b - Submit energy rankings
POST http://localhost:3000/energy/submit
Content-Type: application/json

{
  "sessionId": "11e653aa-4c30-4eac-9f5b-e1b5274f01da",
  "energyStatementGroupId": 10,
  "rankings": [
    { "statementId": 28, "rankId": 3},
    { "statementId": 29, "rankId": 1},
    { "statementId": 30, "rankId": 2}
  ]
}

### 3 - Finish stage 1 of the session
POST http://localhost:3000/energy/finish/11e653aa-4c30-4eac-9f5b-e1b5274f01da


### 4 - Get Personality Test Access
GET http://localhost:3000/personality/access/11e653aa-4c30-4eac-9f5b-e1b5274f01da


### 5 - Post Personality - start session - call on after 4 - get access returns true
POST http://localhost:3000/personality/start/11e653aa-4c30-4eac-9f5b-e1b5274f01da


### Get Personality Session Status
GET http://localhost:3000/personality/11e653aa-4c30-4eac-9f5b-e1b5274f01da/status


//**************************************************
//  Personality Test
//
//**************************************************
### 6a - Get next Personality question
GET http://localhost:3000/personality/11e653aa-4c30-4eac-9f5b-e1b5274f01da/HEAD/next


### 6b Submit Personality answer
POST http://localhost:3000/personality/11e653aa-4c30-4eac-9f5b-e1b5274f01da/HEAD/answer
Content-Type: application/json

{
  "questionId": 90,
  "rankChoiceId": 2
} 


### 7 - get next energy center to determine personality type to run in 6a and 6b
GET http://localhost:3000/personality/next-center/11e653aa-4c30-4eac-9f5b-e1b5274f01da
